### ISSUE TITLE
Option to beautify the output JSON

### ISSUE THREAD

**Issue by philwareham** [ElForastero/webpack-manifest-version-sync-plugin#4]
Hi, thanks for the plugin - very handy!

Would be nice if we could keep the indentation of the original manifest file (currently the generated JSON file has space and newlines stripped). Is that possible?

**Comment by ElForastero** [comment]
@philwareham Hi,

Yeah, I think we can just pass indentation level to `JSON.stringify()`.
Will this cover your needs?

**Comment by philwareham** [comment]
Yes I think that would work, thanks.

**Comment by ElForastero** [comment]
Done. New version is already in npm.

**Comment by philwareham** [comment]
Thanks - works great! Have a good day.
